import {Roboto} from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import {CartProvider} from "@/lib/context/CartContext";
import {WishlistProvider} from "@/lib/context/WishlistContext";
import { LangProvider } from "@/lib/context/LangContext"
import { ProductsProvider } from "@/lib/context/ProductsContext";

const geistRoboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App", // Заполнить надо
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
    <body
      className={`${geistRoboto.variable} antialiased `}
    >
    <LangProvider>
      <ProductsProvider>
        <CartProvider>
          <WishlistProvider>
            <Header/>
            {children}
            <Footer/>
          </WishlistProvider>
        </CartProvider>
      </ProductsProvider>
    </LangProvider>
    </body>
    </html>
  );
}
